'use client'
import React from 'react'
import dynamic from 'next/dynamic'

const componentPreviews: Record<string, any> = {
  text:      dynamic(() => import('@/components/previews/TextPreview'),      { ssr: false }),
  icon:      dynamic(() => import('@/components/previews/IconPreview'),      { ssr: false }),
  spinner:   dynamic(() => import('@/components/previews/SpinnerPreview'),   { ssr: false }),
  separator: dynamic(() => import('@/components/previews/SeparatorPreview'), { ssr: false }),
  button: dynamic(() => import('@/components/previews/ButtonPreview'), { ssr: false }),
  input: dynamic(() => import('@/components/previews/InputPreview'), { ssr: false }),
  textarea: dynamic(() => import('@/components/previews/TextareaPreview'), { ssr: false }),
  checkbox: dynamic(() => import('@/components/previews/CheckboxPreview'), { ssr: false }),
  radio: dynamic(() => import('@/components/previews/RadioPreview'), { ssr: false }),
  slider: dynamic(() => import('@/components/previews/SliderPreview'), { ssr: false }),
  select: dynamic(() => import('@/components/previews/SelectPreview'), { ssr: false }),
  'otp-input': dynamic(() => import('@/components/previews/OtpInputPreview'), { ssr: false }),
  switch: dynamic(() => import('@/components/previews/SwitchPreview'), { ssr: false }),
  badge: dynamic(() => import('@/components/previews/BadgePreview'), { ssr: false }),
  avatar: dynamic(() => import('@/components/previews/AvatarPreview'), { ssr: false }),
  progress: dynamic(() => import('@/components/previews/ProgressPreview'), { ssr: false }),
  toast: dynamic(() => import('@/components/previews/ToastPreview'), { ssr: false }),
  tag: dynamic(() => import('@/components/previews/TagPreview'), { ssr: false }),
  skeleton: dynamic(() => import('@/components/previews/SkeletonPreview'), { ssr: false }),
  card: dynamic(() => import('@/components/previews/CardPreview'), { ssr: false }),
  alert: dynamic(() => import('@/components/previews/AlertPreview'), { ssr: false }),
  modal: dynamic(() => import('@/components/previews/ModalPreview'), { ssr: false }),
  'action-sheet': dynamic(() => import('@/components/previews/ActionSheetPreview'), { ssr: false }),
  accordion: dynamic(() => import('@/components/previews/AccordionPreview'), { ssr: false }),
  tabs: dynamic(() => import('@/components/previews/TabsPreview'), { ssr: false }),
  'empty-state': dynamic(() => import('@/components/previews/EmptyStatePreview'), { ssr: false }),
  sheet: dynamic(() => import('@/components/previews/SheetPreview'), { ssr: false }),
  screen: dynamic(() => import('@/components/previews/ScreenPreview'), { ssr: false }),
  'cart-item': dynamic(() => import('@/components/previews/CartItemPreview'), { ssr: false }),
  'payment-card': dynamic(() => import('@/components/previews/PaymentCardPreview'), { ssr: false }),
  'pricing-card': dynamic(() => import('@/components/previews/PricingCardPreview'), { ssr: false }),
  'product-card': dynamic(() => import('@/components/previews/ProductCardPreview'), { ssr: false }),
  'quantity-stepper': dynamic(() => import('@/components/previews/QuantityStepperPreview'), { ssr: false }),
  'review-card': dynamic(() => import('@/components/previews/ReviewCardPreview'), { ssr: false }),
  'stat-card': dynamic(() => import('@/components/previews/StatCardPreview'), { ssr: false }),
  'countdown': dynamic(() => import('@/components/previews/CountdownPreview'), { ssr: false }),
  'notification-card': dynamic(() => import('@/components/previews/NotificationCardPreview'), { ssr: false }),
  'chip': dynamic(() => import('@/components/previews/ChipPreview'), { ssr: false }),
  'color-picker': dynamic(() => import('@/components/previews/ColorPickerPreview'), { ssr: false }),
  'date-picker': dynamic(() => import('@/components/previews/DatePickerPreview'), { ssr: false }),
  'mention-input': dynamic(() => import('@/components/previews/MentionInputPreview'), { ssr: false }),
  'phone-input': dynamic(() => import('@/components/previews/PhoneInputPreview'), { ssr: false }),
  'pin-lock': dynamic(() => import('@/components/previews/PinLockPreview'), { ssr: false }),
  'rating': dynamic(() => import('@/components/previews/RatingPreview'), { ssr: false }),
  'search-bar': dynamic(() => import('@/components/previews/SearchBarPreview'), { ssr: false }),
  'segmented-control': dynamic(() => import('@/components/previews/SegmentedControlPreview'), { ssr: false }),
  'social-login-button': dynamic(() => import('@/components/previews/SocialLoginButtonPreview'), { ssr: false }),
  'toggle-group': dynamic(() => import('@/components/previews/ToggleGroupPreview'), { ssr: false }),
  'stepper': dynamic(() => import('@/components/previews/StepperPreview'), { ssr: false }),
  'file-upload': dynamic(() => import('@/components/previews/FileUploadPreview'), { ssr: false }),
  'draggable-list': dynamic(() => import('@/components/previews/DraggableListPreview'), { ssr: false }),
  'swipeable-row': dynamic(() => import('@/components/previews/SwipeableRowPreview'), { ssr: false }),
  'fab': dynamic(() => import('@/components/previews/FabPreview'), { ssr: false }),
  'speed-dial': dynamic(() => import('@/components/previews/SpeedDialPreview'), { ssr: false }),
  'audio-player': dynamic(() => import('@/components/previews/AudioPlayerPreview'), { ssr: false }),
  banner: dynamic(() => import('@/components/previews/BannerPreview'), { ssr: false }),
  carousel: dynamic(() => import('@/components/previews/CarouselPreview'), { ssr: false }),
  'chat-bubble': dynamic(() => import('@/components/previews/ChatBubblePreview'), { ssr: false }),
  comment: dynamic(() => import('@/components/previews/CommentPreview'), { ssr: false }),
  'data-table': dynamic(() => import('@/components/previews/DataTablePreview'), { ssr: false }),
  image: dynamic(() => import('@/components/previews/ImagePreview'), { ssr: false }),
  'list-item': dynamic(() => import('@/components/previews/ListItemPreview'), { ssr: false }),
  markdown: dynamic(() => import('@/components/previews/MarkdownPreview'), { ssr: false }),
  timeline: dynamic(() => import('@/components/previews/TimelinePreview'), { ssr: false }),
  'video-player': dynamic(() => import('@/components/previews/VideoPlayerPreview'), { ssr: false }),
  'reaction-bar': dynamic(() => import('@/components/previews/ReactionBarPreview'), { ssr: false }),
  'divider-label': dynamic(() => import('@/components/previews/DividerLabelPreview'), { ssr: false }),
  'biometric-prompt': dynamic(() => import('@/components/previews/BiometricPromptPreview'), { ssr: false }),
  'bottom-sheet-list': dynamic(() => import('@/components/previews/BottomSheetListPreview'), { ssr: false }),
  dialog: dynamic(() => import('@/components/previews/DialogPreview'), { ssr: false }),
  'dropdown-menu': dynamic(() => import('@/components/previews/DropdownMenuPreview'), { ssr: false }),
  popover: dynamic(() => import('@/components/previews/PopoverPreview'), { ssr: false }),
  'bottom-bar': dynamic(() => import('@/components/previews/BottomBarPreview'), { ssr: false }),
  breadcrumb: dynamic(() => import('@/components/previews/BreadcrumbPreview'), { ssr: false }),
  header: dynamic(() => import('@/components/previews/HeaderPreview'), { ssr: false }),
  collapsible: dynamic(() => import('@/components/previews/CollapsiblePreview'), { ssr: false }),
  'onboarding-screen': dynamic(() => import('@/components/previews/OnboardingScreenPreview'), { ssr: false }),
  'infinite-scroll': dynamic(() => import('@/components/previews/InfiniteScrollPreview'), { ssr: false }),
  'pull-to-refresh': dynamic(() => import('@/components/previews/PullToRefreshPreview'), { ssr: false }),
  tooltip: dynamic(() => import('@/components/previews/TooltipPreview'), { ssr: false }),
}

export function ComponentPreview({ slug, part }: { slug: string; part?: string }) {
  const Preview = componentPreviews[slug]
  if (!Preview) return null
  return <Preview part={part} />
}
