import type { Meta, StoryObj } from '@storybook/react-native'
import { useState } from 'react'
import { View } from 'react-native'
import { Text } from '../../../packages/core/src/components/Text/Text'
import { Textarea } from '../../../packages/registry/components/textarea/textarea'

const meta: Meta = {
  title: 'Forms/Textarea',
}

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = {
  render: () => {
    const [value, setValue] = useState('')
    return (
      <View style={{ padding: 16 }}>
        <Textarea label="Bio" placeholder="Tell us about yourself..." value={value} onChangeText={setValue} />
      </View>
    )
  },
}

export const Required: Story = {
  render: () => (
    <View style={{ padding: 16 }}>
      <Textarea label="Description" placeholder="Required field..." required />
    </View>
  ),
}

export const MinMaxRows: Story = {
  render: () => {
    const [value, setValue] = useState('')
    return (
      <View style={{ padding: 16 }}>
        <Textarea label="Message" placeholder="Grows from 2 to 6 rows..." minRows={2} maxRows={6} value={value} onChangeText={setValue} />
      </View>
    )
  },
}

export const CharacterCount: Story = {
  render: () => (
    <View style={{ padding: 16 }}>
      <Textarea label="Tweet" placeholder="What's on your mind?" showCount maxLength={280} countWarnAt={0.8} />
    </View>
  ),
}

export const FloatingLabel: Story = {
  render: () => {
    const [value, setValue] = useState('')
    return (
      <View style={{ padding: 16 }}>
        <Textarea floatingLabel label="Notes" placeholder="Add notes..." value={value} onChangeText={setValue} />
      </View>
    )
  },
}

export const SubmitOnEnter: Story = {
  render: () => {
    const [value, setValue] = useState('')
    const [sent, setSent] = useState<string[]>([])
    return (
      <View style={{ padding: 16, gap: 8 }}>
        <Textarea
          label="Send a message"
          placeholder="Press Enter to send..."
          submitOnEnter
          onSubmit={(v) => { if (v.trim()) { setSent(p => [...p, v]); setValue('') } }}
          value={value}
          onChangeText={setValue}
          minRows={1}
          maxRows={4}
        />
        {sent.map((m, i) => (
          <Text key={i} variant="caption" muted>→ {m}</Text>
        ))}
      </View>
    )
  },
}

export const MentionDetection: Story = {
  render: () => {
    const [query, setQuery] = useState('')
    return (
      <View style={{ padding: 16, gap: 8 }}>
        <Textarea label="Comment" placeholder="Type @ to mention..." onMention={setQuery} minRows={2} />
        {query !== '' && <Text variant="caption" muted>Query: @{query}</Text>}
      </View>
    )
  },
}

export const VoiceInput: Story = {
  render: () => (
    <View style={{ padding: 16 }}>
      <Textarea label="Voice note" placeholder="Tap 🎙 to dictate..." voiceInput onVoicePress={() => {}} />
    </View>
  ),
}

export const ReadOnly: Story = {
  render: () => (
    <View style={{ padding: 16 }}>
      <Textarea label="Terms" value="By using native-mate you agree to the terms of service." readOnly />
    </View>
  ),
}

export const WithError: Story = {
  render: () => (
    <View style={{ padding: 16 }}>
      <Textarea label="Review" error="Review cannot be empty" />
    </View>
  ),
}

export const WithHint: Story = {
  render: () => (
    <View style={{ padding: 16 }}>
      <Textarea label="Bio" hint="Max 500 characters" placeholder="Tell us about yourself..." showCount maxLength={500} />
    </View>
  ),
}

export const Disabled: Story = {
  render: () => (
    <View style={{ padding: 16 }}>
      <Textarea label="System Notes" value="Auto-generated by system." disabled />
    </View>
  ),
}

export const AllStates: Story = {
  render: () => (
    <View style={{ padding: 16, gap: 16 }}>
      <Textarea label="Default" placeholder="Placeholder" />
      <Textarea label="Required" placeholder="Placeholder" required />
      <Textarea label="With error" placeholder="Placeholder" error="This field is required" />
      <Textarea label="With hint" placeholder="Placeholder" hint="Must be descriptive" />
      <Textarea label="With count" placeholder="Placeholder" showCount maxLength={200} />
      <Textarea label="Disabled" placeholder="Placeholder" disabled />
      <Textarea label="Read-only" value="Cannot be edited" readOnly />
    </View>
  ),
}
