'use client'
import React, { useState } from 'react'
import { View } from 'react-native'
import { Text } from '@native-mate/core'
import { Preview } from './shared/Preview'
import { Textarea } from '../../../../packages/registry/components/textarea/textarea'

export default function TextareaPreview() {
  const [bio, setBio] = useState('')
  const [msg, setMsg] = useState('')
  const [chat, setChat] = useState('')
  const [chatMessages, setChatMessages] = useState<string[]>([])
  const [mention, setMention] = useState('')
  const [notes, setNotes] = useState('')

  return (
    <div className="space-y-10">
      <Preview title="Default" code={`import { Textarea } from '~/components/ui/textarea'

<Textarea label="Bio" placeholder="Tell us about yourself..." />`}>
        <View style={{ width: '100%', maxWidth: 380 }}>
          <Textarea label="Bio" placeholder="Tell us about yourself..." value={bio} onChangeText={setBio} />
        </View>
      </Preview>

      <Preview title="Min & max rows" code={`<Textarea
  label="Message"
  placeholder="Grows from 2 to 6 rows..."
  minRows={2}
  maxRows={6}
/>`}>
        <View style={{ width: '100%', maxWidth: 380 }}>
          <Textarea label="Message" placeholder="Grows from 2 to 6 rows..." minRows={2} maxRows={6} value={msg} onChangeText={setMsg} />
        </View>
      </Preview>

      <Preview title="Character count" code={`<Textarea label="Tweet" showCount maxLength={100} countWarnAt={0.8} />`}>
        <View style={{ width: '100%', maxWidth: 380 }}>
          <Textarea label="Tweet" placeholder="What's on your mind?" showCount maxLength={100} countWarnAt={0.8} />
        </View>
      </Preview>

      <Preview title="Floating label" code={`<Textarea floatingLabel label="Notes" placeholder="Add notes..." />`}>
        <View style={{ width: '100%', maxWidth: 380 }}>
          <Textarea floatingLabel label="Notes" placeholder="Add notes..." value={notes} onChangeText={setNotes} />
        </View>
      </Preview>

      <Preview title="Submit on Enter (Slack-style)" code={`<Textarea
  label="Send a message"
  placeholder="Press Enter to send..."
  submitOnEnter
  onSubmit={(val) => sendMessage(val)}
  minRows={1}
  maxRows={4}
/>`}>
        <View style={{ width: '100%', maxWidth: 380, gap: 8 }}>
          <Textarea
            label="Send a message"
            placeholder="Press Enter to send…"
            submitOnEnter
            onSubmit={(val) => {
              if (val.trim()) setChatMessages(p => [...p, val])
            }}
            value={chat}
            onChangeText={setChat}
            minRows={1}
            maxRows={4}
          />
          {chatMessages.slice(-3).map((m, i) => (
            <Text key={i} style={{ fontSize: 12, color: '#71717a' }}>→ {m}</Text>
          ))}
        </View>
      </Preview>

      <Preview title="Mention detection (@)" code={`<Textarea
  label="Comment"
  placeholder="Type @ to mention someone..."
  onMention={(query) => fetchUsers(query)}
/>`}>
        <View style={{ width: '100%', maxWidth: 380 }}>
          <Textarea
            label="Comment"
            placeholder="Type @ to mention someone..."
            onMention={(q) => setMention(q)}
            minRows={2}
          />
          {mention !== '' && <Text style={{ fontSize: 12, color: '#71717a', marginTop: 4 }}>Mention query: @{mention}</Text>}
        </View>
      </Preview>

      <Preview title="Error & disabled" code={`<Textarea label="Review" error="Review cannot be empty" />
<Textarea label="System Notes" value="Auto-generated." disabled />`}>
        <View style={{ gap: 12, width: '100%', maxWidth: 380 }}>
          <Textarea label="Review" error="Review cannot be empty" />
          <Textarea label="System Notes" value="Auto-generated by system." disabled />
        </View>
      </Preview>
    </div>
  )
}
